import os
import re
from flask import Flask, render_template, request, jsonify, send_from_directory, abort

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'aravind-portfolio-secret-key-2026')

# Projects detailed dataset
PROJECTS_DATA = [
    {
        "id": 1,
        "title": "ECG, EMG & EOG Signal Anomaly Detection",
        "category": "biomedical",
        "category_label": "Biomedical AI",
        "short_desc": "Real-time biomedical signal acquisition using BioAmp EXG + ESP32. TensorFlow ML models classify cardiac and muscular anomalies with live health monitoring alerts.",
        "full_desc": "An end-to-end intelligent biomedical diagnostic system that captures analog bio-potential signals (ECG for heart rhythm, EMG for neuromuscular activity, EOG for ocular movement) via BioAmp EXG sensors. The signals are digitized and filtered on ESP32, streamed over Wi-Fi/WebSockets, and evaluated using deep learning (CNN & LSTM) anomaly detection models in TensorFlow to identify arrhythmias and muscle fatigue in real time.",
        "hardware": ["BioAmp EXG Sensor", "ESP32 Microcontroller", "Gel Electrodes", "Analog Filters", "Wi-Fi Module"],
        "software": ["Python 3.11", "TensorFlow / Keras", "ESP-IDF / Arduino C++", "NumPy & SciPy", "Flask WebSockets"],
        "tags": ["Python", "TensorFlow", "ESP32", "Signal Processing", "Keras"],
        "icon": "bi-heart-pulse",
        "gradient": "linear-gradient(135deg, #1a56db 0%, #0ea5e9 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 2,
        "title": "EOG-Controlled Wheelchair with Fall Detection",
        "category": "assistive",
        "category_label": "Assistive Tech",
        "short_desc": "Hands-free wheelchair controlled by Electrooculography (EOG) eye movement signals with integrated accelerometer fall detection and automated caregiver alerts.",
        "full_desc": "Designed to empower severely paralyzed individuals (e.g., ALS, quadriplegia). Eye movements (left glance, right glance, vertical saccades, blinks) are recorded via surface electrodes, filtered using bandpass analog filters, and classified to drive dual DC motor wheelchair tracks. An onboard MPU6050 IMU continuously monitors sudden tilt anomalies or impact shocks, immediately halting motors and transmitting emergency GPS coordinates to caregivers via GSM.",
        "hardware": ["EOG BioAmp Sensor", "ESP32 DevKit", "MPU6050 Accelerometer/Gyroscope", "L298N Motor Driver", "SIM800L GSM Module", "12V DC Motors"],
        "software": ["C++ / Arduino IDE", "Python Signal Classifier", "Embedded Firmware", "GSM AT Commands"],
        "tags": ["Arduino", "ESP32", "EOG Sensors", "Python", "Motor Control"],
        "icon": "bi-person-wheelchair",
        "gradient": "linear-gradient(135deg, #059669 0%, #34d399 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 3,
        "title": "EMG-Based Smart Wheelchair Navigation",
        "category": "assistive",
        "category_label": "Neuro-Tech",
        "short_desc": "Muscle contraction EMG signals mapped to wheelchair commands using ML classification for users with severe motor disabilities.",
        "full_desc": "Utilizes Electromyography (EMG) to measure micro-voltage electrical activity generated by voluntary muscle contractions (e.g. forearm, jaw, or bicep flexing). Features a custom hardware amplification stage with low-noise instrumentation amplifiers, followed by feature extraction (Root Mean Square, Mean Absolute Value, Waveform Length) and a real-time machine learning classifier achieving high responsiveness and low false-positive rates.",
        "hardware": ["EMG Muscle Sensor", "ESP32 MCU", "Instrumentation Amp", "H-Bridge Motor Driver", "Chassis & Wheelchair Rig"],
        "software": ["Python", "Scikit-Learn", "Arduino C++", "NumPy", "Real-time Signal DSP"],
        "tags": ["Arduino IDE", "EMG Sensors", "Python", "ML", "Edge AI"],
        "icon": "bi-activity",
        "gradient": "linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 4,
        "title": "Smart Agriculture AI & Threat Detection Platform",
        "category": "vision",
        "category_label": "Smart Agriculture",
        "short_desc": "IoT + AI platform using CNN for leaf disease detection, wildlife intrusion deterrence, and environmental sensors for precision farming alerts.",
        "full_desc": "A smart precision agriculture ecosystem combining computer vision and edge IoT nodes. Deep convolutional neural networks (CNNs) analyze real-time camera feeds to identify foliar crop diseases across 15+ plant species and detect nocturnal wildlife/animal intrusions. Environmental sensor nodes (soil moisture, temperature, humidity, light) dynamically regulate irrigation valves and send instant SMS/Telegram alerts to farmers.",
        "hardware": ["ESP32-CAM", "Raspberry Pi", "Soil Moisture Sensors", "DHT22 Sensor", "Solenoid Water Valves", "Solar Power Unit"],
        "software": ["Python", "TensorFlow / Keras", "OpenCV", "CNN Architecture", "Flask Dashboard", "Twilio API"],
        "tags": ["Python", "TensorFlow", "OpenCV", "CNN", "IoT Sensors"],
        "icon": "bi-tree",
        "gradient": "linear-gradient(135deg, #d97706 0%, #fbbf24 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 5,
        "title": "Airbag Collision Detection & Safety System",
        "category": "safety",
        "category_label": "Safety System",
        "short_desc": "MPU6050 IMU detects high-impact collisions, triggers servo-motor airbag simulation, and sends emergency SMS alerts via GSM when G-force exceeds threshold.",
        "full_desc": "An automotive safety module that utilizes high-speed polling of an MPU6050 triple-axis accelerometer. When severe G-force deceleration exceeding pre-calibrated safety boundaries is detected, the controller triggers instantaneous servo-motor airbag deployment in under 25 milliseconds, while concurrently dispatching automated distress SMS messages containing vehicle telemetry to emergency services.",
        "hardware": ["Arduino Nano / ESP32", "MPU6050 IMU", "High-Torque Servo Motor", "SIM800L GSM Module", "Buzzer & Strobe LED"],
        "software": ["Embedded C++", "Kalman Filter Algorithm", "GSM AT Command Protocol"],
        "tags": ["Arduino", "C++", "MPU6050", "GSM", "Embedded"],
        "icon": "bi-shield-check",
        "gradient": "linear-gradient(135deg, #dc2626 0%, #f87171 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 6,
        "title": "Non-Invasive Anemia Screening System",
        "category": "biomedical",
        "category_label": "Healthcare",
        "short_desc": "Non-invasive anemia screening using sensor-based optical health monitoring to detect hemoglobin anomalies without needle blood tests.",
        "full_desc": "A non-invasive, painless diagnostic screening tool developed to evaluate hemoglobin concentrations. Utilizing multi-wavelength optical PPG sensors and machine learning regression algorithms, the device correlates light absorption differentials through the fingertip/palpebral conjunctiva to estimate hemoglobin levels, offering instant screening in rural and resource-limited clinics.",
        "hardware": ["MAX30102 / Optical Sensor", "ESP32 Microcontroller", "OLED Display 0.96 inch", "Rechargeable LiPo Battery"],
        "software": ["Python", "Scikit-Learn Regression", "Arduino IDE", "Data Preprocessing"],
        "tags": ["Arduino", "Sensors", "Python", "Healthcare ML"],
        "icon": "bi-droplet-half",
        "gradient": "linear-gradient(135deg, #7c3aed 0%, #c084fc 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 7,
        "title": "Automatic Railway Level Gate Control",
        "category": "safety",
        "category_label": "Automation",
        "short_desc": "IR proximity sensors detect approaching trains to automatically control level-crossing gates with audio/visual warnings and real-time automation.",
        "full_desc": "An automated infrastructure safety solution engineered to eliminate accidents at un-manned railway crossings. Infrared obstacle and proximity sensor pairs deployed at track boundaries calculate train approach velocity and arrival timestamps, automatically triggering gate barrier servomotors, signal lights, and warning sirens, with failsafe override mechanisms.",
        "hardware": ["Arduino Mega", "IR Transceiver Sensor Arrays", "Servo Motors", "LED Light Columns", "Alarm Siren"],
        "software": ["Embedded C++", "State Machine Logic", "Timer Interrupts"],
        "tags": ["Arduino", "IR Sensors", "C++", "Servo Motor", "Automation"],
        "icon": "bi-train-front",
        "gradient": "linear-gradient(135deg, #0d9488 0%, #2dd4bf 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    },
    {
        "id": 8,
        "title": "Alcohol Detection & Smart Engine Lock for Cars",
        "category": "safety",
        "category_label": "Driver Safety",
        "short_desc": "MQ-3 sensor detects driver intoxication above legal BAC, disables vehicle ignition via relay, and sends GPS-tagged emergency SMS via GSM module.",
        "full_desc": "A smart preventative automotive system designed to eradicate drunk driving. An MQ-3 semiconductor sensor continuously samples cabin air near the steering column. If blood alcohol content (BAC) surpasses safe thresholds, the system disables the ignition relay preventing engine start, sounds an intermittent alert, and dispatches a GPS-tagged SMS alert to fleet managers or family members.",
        "hardware": ["MQ-3 Gas Sensor", "Arduino Uno / ESP32", "5V Relay Module", "NEO-6M GPS Module", "SIM800L GSM"],
        "software": ["C++ / Arduino", "GPS NMEA Parser", "GSM Alert System"],
        "tags": ["Arduino", "MQ-3", "GSM", "GPS", "Safety"],
        "icon": "bi-car-front",
        "gradient": "linear-gradient(135deg, #ea580c 0%, #fb923c 100%)",
        "github_url": "https://github.com/Aravindkumar1718",
        "live_demo_available": True
    }
]

# Technical skills data (clean, modern, no progress bars or levels)
SKILLS_DATA = {
    "programming": {
        "title": "Programming",
        "icon": "bi-code-slash",
        "color_class": "blue",
        "skills": [
            {"name": "Python", "icon": "bi-filetype-py"},
            {"name": "C", "icon": "bi-file-code"},
            {"name": "HTML", "icon": "bi-filetype-html"},
            {"name": "CSS", "icon": "bi-filetype-css"},
            {"name": "JavaScript (Basic)", "icon": "bi-filetype-js"}
        ]
    },
    "iot": {
        "title": "IoT & Embedded Systems",
        "icon": "bi-motherboard",
        "color_class": "green",
        "skills": [
            {"name": "Arduino IDE", "icon": "bi-motherboard-fill"},
            {"name": "ESP32", "icon": "bi-cpu-fill"},
            {"name": "Raspberry Pi", "icon": "bi-hdd-network"},
            {"name": "Sensor Integration", "icon": "bi-broadcast"},
            {"name": "Real-Time Data Acquisition", "icon": "bi-reception-4"},
            {"name": "Signal Processing", "icon": "bi-activity"}
        ]
    },
    "web_dev": {
        "title": "Web Development",
        "icon": "bi-globe",
        "color_class": "sky",
        "skills": [
            {"name": "Flask", "icon": "bi-server"},
            {"name": "RESTful APIs", "icon": "bi-cloud-arrow-down"},
            {"name": "SQL", "icon": "bi-database"}
        ]
    },
    "ml_ai": {
        "title": "Machine Learning & AI",
        "icon": "bi-cpu",
        "color_class": "purple",
        "skills": [
            {"name": "TensorFlow", "icon": "bi-lightning-fill"},
            {"name": "Keras", "icon": "bi-gear-fill"},
            {"name": "PyTorch", "icon": "bi-fire"},
            {"name": "CNN", "icon": "bi-image"},
            {"name": "Image Processing", "icon": "bi-camera"}
        ]
    },
    "data_science": {
        "title": "Data Science",
        "icon": "bi-bar-chart-line",
        "color_class": "amber",
        "skills": [
            {"name": "Pandas", "icon": "bi-table"},
            {"name": "NumPy", "icon": "bi-calculator"},
            {"name": "Matplotlib", "icon": "bi-pie-chart"},
            {"name": "Seaborn", "icon": "bi-bar-chart"},
            {"name": "Data Preprocessing", "icon": "bi-funnel"}
        ]
    }
}

# Contact submissions storage (in-memory for demo / extensible to db)
CONTACT_MESSAGES = []

@app.route('/')
def home():
    """Renders the portfolio home page with all dynamic data."""
    return render_template(
        'index.html',
        projects=PROJECTS_DATA,
        skills=SKILLS_DATA
    )

@app.route('/download-resume')
@app.route('/download-cv')
def download_resume():
    """Serves Aravind's Resume document (PDF default, or DOCX) as a direct attachment download."""
    doc_format = request.args.get('format', 'pdf').lower()
    docs_dir = os.path.join(app.root_path, 'static', 'docs')
    
    if doc_format == 'docx':
        filename = 'Aravind_Kumar_V_Resume.docx'
        # fallback filenames
        if not os.path.exists(os.path.join(docs_dir, filename)):
            filename = 'Aravind_Kumar_V_CV.docx'
        mimetype = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        download_name = 'Aravind_Kumar_V_Resume.docx'
    else:
        filename = 'Aravind_Kumar_V_Resume.pdf'
        mimetype = 'application/pdf'
        download_name = 'Aravind_Kumar_V_Resume.pdf'
    
    if os.path.exists(os.path.join(docs_dir, filename)):
        return send_from_directory(
            docs_dir,
            filename,
            as_attachment=True,
            mimetype=mimetype,
            download_name=download_name
        )
    elif os.path.exists(os.path.join(app.root_path, 'assets', filename)):
        return send_from_directory(
            os.path.join(app.root_path, 'assets'),
            filename,
            as_attachment=True,
            mimetype=mimetype,
            download_name=download_name
        )
    elif os.path.exists(os.path.join(app.root_path, filename)):
        return send_from_directory(
            app.root_path,
            filename,
            as_attachment=True,
            mimetype=mimetype,
            download_name=download_name
        )
    abort(404, description="Resume file not found")

@app.route('/download-resume/pdf')
def download_resume_pdf():
    """Explicit endpoint for PDF resume download."""
    docs_dir = os.path.join(app.root_path, 'static', 'docs')
    return send_from_directory(
        docs_dir,
        'Aravind_Kumar_V_Resume.pdf',
        as_attachment=True,
        mimetype='application/pdf',
        download_name='Aravind_Kumar_V_Resume.pdf'
    )

@app.route('/download-resume/docx')
def download_resume_docx():
    """Explicit endpoint for Word DOCX resume download."""
    docs_dir = os.path.join(app.root_path, 'static', 'docs')
    return send_from_directory(
        docs_dir,
        'Aravind_Kumar_V_Resume.docx',
        as_attachment=True,
        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        download_name='Aravind_Kumar_V_Resume.docx'
    )

@app.route('/view-resume')
def view_resume():
    """Inline browser view of PDF resume."""
    docs_dir = os.path.join(app.root_path, 'static', 'docs')
    return send_from_directory(
        docs_dir,
        'Aravind_Kumar_V_Resume.pdf',
        as_attachment=False,
        mimetype='application/pdf'
    )


@app.route('/api/projects', methods=['GET'])
def get_projects():
    """Returns the list of all projects with complete metadata."""
    category = request.args.get('category')
    if category and category != 'all':
        filtered = [p for p in PROJECTS_DATA if p['category'] == category]
        return jsonify({"success": True, "count": len(filtered), "projects": filtered})
    return jsonify({"success": True, "count": len(PROJECTS_DATA), "projects": PROJECTS_DATA})

@app.route('/api/projects/<int:project_id>', methods=['GET'])
def get_project_detail(project_id):
    """Returns single project technical specs."""
    project = next((p for p in PROJECTS_DATA if p['id'] == project_id), None)
    if not project:
        return jsonify({"success": False, "error": "Project not found"}), 404
    return jsonify({"success": True, "project": project})

@app.route('/api/contact', methods=['POST'])
def handle_contact():
    """Handles contact form AJAX submissions with validation."""
    data = request.get_json() or request.form
    
    name = (data.get('name') or '').strip()
    email = (data.get('email') or '').strip()
    subject = (data.get('subject') or '').strip()
    message = (data.get('message') or '').strip()

    # Form Validation
    if not name or len(name) < 2:
        return jsonify({
            "success": False,
            "error": "Please provide a valid name (at least 2 characters)."
        }), 400

    email_regex = r"^[\w\.-]+@[\w\.-]+\.\w+$"
    if not email or not re.match(email_regex, email):
        return jsonify({
            "success": False,
            "error": "Please provide a valid email address."
        }), 400

    if not message or len(message) < 5:
        return jsonify({
            "success": False,
            "error": "Please write a message with at least 5 characters."
        }), 400

    # Store message
    record = {
        "name": name,
        "email": email,
        "subject": subject if subject else "General Inquiry",
        "message": message
    }
    CONTACT_MESSAGES.append(record)

    return jsonify({
        "success": True,
        "message": f"Thank you, {name}! Your message has been received successfully. I will get back to you shortly."
    }), 200

@app.errorhandler(404)
def page_not_found(e):
    return jsonify({"error": "Resource not found", "status": 404}), 404

@app.errorhandler(500)
def server_error(e):
    return jsonify({"error": "Internal server error", "status": 500}), 500

if __name__ == '__main__':
    # Run locally on port 5000 in debug mode
    app.run(host='0.0.0.0', port=5000, debug=True)
